docs: express middleware
prici-io/prici pull request #36
Opened 2024-01-27 16:24 UTC by madina0801

Issue #30 
Please, let me know if you'd like to have a more clear documentation and where it should be located :)

2024-01-27 18:02 UTC, davidmeirlevy requested changes

2024-01-27 18:02 UTC, davidmeirlevy commented on documentation/content/sdk/node/get-express-middleware.md
> +const { getExpressMiddleware } = require('your-module');
It's coming from "@prici/sdk/express"

2024-01-27 18:02 UTC, davidmeirlevy commented on documentation/content/sdk/node/get-express-middleware.md
> +  incrementAmount: // Optional: Specify the increment amount,
There are also "getX" for every property, that allows a sun functions for each property.

2024-01-27 18:03 UTC, davidmeirlevy commented
Thanks for the docs.

Please fix the two comments, and also add a link to this page on .vitepress/config.js

2024-01-30 04:17 UTC, madina0801 commented
Written more detailed docs on middleware options, example usage and updated config :)

2024-01-30 04:54 UTC, davidmeirlevy commented
Thanks!

Looks good.

2024-01-30 04:54 UTC, merged